service: lambda-powertools-demo

plugins:
  - serverless-iam-roles-per-function
  - serverless-step-functions
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-2
  environment:
    STAGE: dev
    DATADOG_API_KEY: idunno
    DATADOG_PREFIX: lambda-powertools-demo.

functions:
  api-a:
    handler: functions/api-a.handler
    events:
      - http:
          path: /
          method: get
    iamRoleStatements:
      - Effect: Allow
        Action: kinesis:PutRecord
        Resource: 
          Fn::GetAtt:
            - KinesisStream
            - Arn
  
  api-b:
    handler: functions/api-b.handler
    events:
      - http:
          path: /
          method: post

  kinesis:
    handler: functions/kinesis.handler
    events:
      - stream:
          type: kinesis
          arn:
            Fn::GetAtt:
              - KinesisStream
              - Arn
    environment:
      TOPIC_ARN:
        Ref: SnsTopic
    iamRoleStatements:
      - Effect: Allow
        Action: sns:Publish
        Resource:
          Ref: SnsTopic

  sns:
    handler: functions/sns.handler
    events:
      - sns: 
          arn:
            Ref: SnsTopic
          topicName: lambda-powertools-demo
    environment:
      STATE_MACHINE_ARN:
        Ref: LambdaPowertoolsDemo
    iamRoleStatements:
      - Effect: Allow
        Action: states:StartExecution
        Resource: 
          Ref: LambdaPowertoolsDemo
      - Effect: Allow
        Action: lambda:invoke
        Resource:
          Ref: StandDashaloneLambdaFunction

  stand-alone:
    handler: functions/stand-alone.handler

  add:
    handler: functions/add.handler

  double:
    handler: functions/double.handler
    
stepFunctions:
  stateMachines:
    lambda-powertools-demo:      
      name: lambdaPowertoolsDemo
      definition:
        Comment: A demo to show off the Lambda powertools packages
        StartAt: Add
        States:
          Add:
            Type: Task
            Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-dev-add
            ResultPath: $.z
            Next: Double
          Double:
            Type: Task
            Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-dev-double
            ResultPath: $.result
            End: true

resources:
  Resources:
    KinesisStream:
      Type: AWS::Kinesis::Stream
      Properties: 
        Name: lambda-powertools-demo
        ShardCount: 1

    SnsTopic:
      Type: AWS::SNS::Topic      
      Properties: 
        DisplayName: lambda-powertools-demo
        TopicName: lambda-powertools-demo