pipeline:
  npm-auth:
    image: robertstettner/drone-npm-auth
    secrets: [ npm_token ]
    when:
      event: [ push, deployment ]
  setup:
    image: node:10-alpine
    when:
      event: push
    commands:
      - cp ${DRONE_WORKSPACE:-.}/.npmrc ~/
      - npm ci
      - npm run install
  test-12:
    image: node:12-alpine
    group: test
    when:
      event: push
    commands:
      - npm test
  test-10:
    image: node:10-alpine
    group: test
    when:
      event: push
    commands:
      - npm test
  test-8:
    image: node:8-alpine
    group: test
    when:
      event: push
    commands:
      - npm test
  new-version:
    image: node:10
    secrets: [ github_token ]
    when:
      event: push
      branch: master
    commands:
      - git status
      # git complains if you don't set an email for some reason
      - git config user.email "dazn-bot@dazn.com"
      # lerna version --github-release needs the GH_TOKEN, not GITHUB_TOKEN
      - export GH_TOKEN=$GITHUB_TOKEN
      - npm run new-version
  publish:
    image: node:10
    secrets: [ npm_token ]
    when:
      event: push
      branch: master
    commands:
      - npm run publish
