pipeline:
  npm-auth:
    image: robertstettner/drone-npm-auth
    secrets: [ npm_token ]
    when:
      event: [ push, deployment ]
  test:
    image: node:carbon-jessie
    when:
      event: push
    commands:
      - cp ${DRONE_WORKSPACE:-.}/.npmrc ~/
      - npm i
      - npm run install
      - npm test
  new-version:
    image: node:carbon-jessie
    secrets: [ github_token ]
    when:
      event: push
      branch: master
    commands:
      - git status
      # git complains if you don't set an email for some reason
      - git config user.email "dazn-bot@dazn.com"
      # lerna version --github-release needs the GH_TOKEN, not GITHUB_TOKEN
      - export GH_TOKEN=$GITHUB_TOKEN
      - npm run new-version
  publish:
    image: node:carbon-jessie
    secrets: [ npm_token ]
    when:
      event: push
      branch: master
    commands:
      - npm run publish
