pipeline:
  npm-auth:
    image: robertstettner/drone-npm-auth
    secrets: [ npm_token ]
    when:
      event: [ push, deployment ]
  test:
    image: node:carbon-jessie
    when:
      event: push
    commands:
      - cp ${DRONE_WORKSPACE:-.}/.npmrc ~/
      - npm i
      - npm run install
      - npm test
  publish:
    image: node:carbon-jessie
    secrets: [ github_token ]
    when:
      event: push
      branch: master
    commands:
      - git status
      - git config user.email "donot@push.me"
      - git commit -am "Do not push me" --no-verify
      - npm run new-version
      - npm run publish
