version: 2.1
commands:
  install:
    steps:
      - checkout
      - run:
          name: npm auth
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run: npm ci
      - run: npm run install
jobs:
  test-node12:
    docker:
      - image: circleci/node:12
    steps:
      - install
      - run: npm test
  test-node10:
    docker:
      - image: circleci/node:10
    steps:
      - install
      - run: npm test
  test-node8:
    docker:
      - image: circleci/node:8
    steps:
      - install
      - run: npm test
  new-version:
    docker:
      - image: circleci/node:10
    steps:
      - add_ssh_keys
      - install
      - run: git status
      # git complains if you don't set an email for some reason
      - run: git config user.email "dazn-bot@dazn.com"
      - run: npm run new-version
      - persist_to_workspace:
          root: ~/project
          paths: .
  publish:
    docker:
      - image: circleci/node:10
    steps:
      - attach_workspace:
          at: ~/project
      - run: npm run publish
workflows:
  main:
    jobs:
      - test-node12
      - test-node10
      - test-node8
      - new-version:
          requires:
            - test-node12
            - test-node10
            - test-node8
          filters:
            branches:
              only: master
      - publish:
          requires:
            - new-version
          filters:
            branches:
              only: master
