version: 2.1
references:
  persist_to_workspace: &PERSIST_TO_WORKSPACE
    persist_to_workspace:
      root: ~/project
      paths: .
  attach_workspace: &ATTACH_WORKSPACE
    attach_workspace:
      at: ~/project
commands:
  run_tests:
    steps:
      - checkout
      - run: npm test
      - run:
          name: npm auth
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run: npm ci
      - run: npm run install
jobs:
  test-node12:
    docker:
      - image: circleci/node:12
    steps:
      - run_tests
  test-node10:
    docker:
      - image: circleci/node:10
    steps:
      - run_tests
  test-node8:
    docker:
      - image: circleci/node:8
    steps:
      - run_tests
  new-version:
    docker:
      - image: circleci/node:10
    steps:
      - add_ssh_keys
      - run: git status
      # git complains if you don't set an email for some reason
      - run: git config user.email "dazn-bot@dazn.com"
      - run: npm run new-version
      - *PERSIST_TO_WORKSPACE
  publish:
    docker:
      - image: circleci/node:10
    steps:
      - *ATTACH_WORKSPACE
      - run: npm run publish
workflows:
  main:
    jobs:
      - test-node12:
      - test-node10:
      - test-node8:
      - new-version:
          requires:
            - test-node12
            - test-node10
            - test-node8
          filters:
            branches:
              only: master
      - publish:
          requires:
            - new-version
          filters:
            branches:
              only: master
