version: 2.1
references:
  persist_to_workspace: &PERSIST_TO_WORKSPACE
    persist_to_workspace:
      root: ~/project
      paths: .
  attach_workspace: &ATTACH_WORKSPACE
    attach_workspace:
      at: ~/project
commands:
  run_tests:
    steps:
      - run: npm test
jobs:
  build:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - run:
          name: npm auth
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run: npm ci
      - run: npm run install
      - *PERSIST_TO_WORKSPACE
  test-12:
    docker:
      - image: circleci/node:12
    steps:
      - *ATTACH_WORKSPACE
      - run_tests
  test-10:
    docker:
      - image: circleci/node:10
    steps:
      - *ATTACH_WORKSPACE
      - run_tests
  test-8:
    docker:
      - image: circleci/node:8
    steps:
      - *ATTACH_WORKSPACE
      - run_tests

workflows:
  version: 2
  ci:
    jobs:
      - build
      - test-12:
          requires:
            - build
      - test-10:
          requires:
            - build
      - test-8:
          requires:
            - build
